spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_system?characterEncoding=utf-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
server:
  servlet:
    context-path: /order_system

redirect:
  seller:
    order: /order_system/seller/order/list
    product: /order_system/seller/product/list
    category: /order_system/seller/category/list
    aspect:
      login:
        fail: /seller/user/index
    user:
      login:
        fail: /order_system/seller/user/index
        success: /seller/order/list
view:
  success: common/success
  error: common/error