spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_system?characterEncoding=utf-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /order
